apsapg_01^U^in_pid,sub_pid^apsapg^
apsapm_01^U^out_pid,in_pid,sub_pid^apsapm^
apsarm_01^U^pid,rid,compt,sply_rid^apsarm^
apsbmm_01^U^out_pid,in_pid,seq_txt^apsbmm^
apscim_01^U^casecode^apscim^
apscmm_01^U^cm_id,cmg_id^apscmm^
apsdcm_01^U^dcaln_id,d_date^apsdcm^
apsddo_01^U^mo_id,dep_num,prod_num^apsddo^
apsdom_01^U^do_id^apsdom^
apsiam_01^U^pid,oid,wh_id,stk_loc^apsiam^
apsimm_01^U^pid^apsimm^
apsirm_01^U^pid,route_id^apsirm^
apsmrm_01^U^mo_id,in_pid,seq_txt,sequ_num^apsmrm^
apsocm_01^U^opt_pid,feat_pid,do_id,seq_txt^apsocm^
apspfm_01^U^pid,mid^apspfm^
apsrem_01^U^eq_id^apsrem^
apsrgm_01^U^eqg_id,eq_id^apsrgm^
apsrom_01^U^route_id,sequ_num,op_id^apsrom^
apssim_01^U^pid,sup_id^apssim^
apsslm_01^U^wh_id,stk_loc^apsslm^
apssmm_01^U^mo_id^apssmm^
apssmo_01^U^mo_id^apssmo^
apsspm_01^U^po_id^apsspm^
apsspo_01^U^po_id^apsspo^
apssrm_01^U^rid,sply_typ,wh_id,stk_loc^apssrm^
apsuim_01^U^pid,wh_id,stk_loc^apsuim^
apswcm_01^U^wcaln_id^apswcm^
apswhm_01^U^wh_id^apswhm^
apswmm_01^U^wm_id,st_t^apswmm^
apswsm_01^U^ws_id^apswsm^
